# Generated by Django 4.1.7 on 2024-05-24 11:10

import controlsApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Control",
            fields=[
                (
                    "name",
                    models.TextField(primary_key=True, serialize=False, unique=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("controlset_ref", models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name="ControlHierarchy",
            fields=[
                ("slug", models.TextField(primary_key=True, serialize=False)),
                ("controlset_ref", models.JSONField(default=list)),
                ("parents", controlsApp.models.arrField(default=[])),
                ("children", controlsApp.models.arrField(default=[])),
            ],
        ),
        migrations.CreateModel(
            name="ControlSet",
            fields=[
                ("slug", models.TextField(primary_key=True, serialize=False)),
                ("name", models.TextField(unique=True)),
                ("hierarchy_depth", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
